
const DATA=window.VYPJ_DATA||[];
const $=s=>document.querySelector(s);
function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function excerpt(a){return a.paragraphs.find(p=>p.length>80)||a.paragraphs[0]||''}
function card(a){return `<a class="card" href="article.html?slug=${encodeURIComponent(a.slug)}"><div class="type">${esc(a.type)}</div><h3>${esc(a.title)}</h3><p class="excerpt">${esc(excerpt(a).slice(0,190))}${excerpt(a).length>190?'…':''}</p><div class="meta">${esc(a.author)}</div></a>`}
function renderHome(){let root=$('#content'); if(!root)return; root.innerHTML=`<section class="hero"><div class="kicker">Vietnam Youth Policy Journal</div><h1>Young people thinking seriously about policy.</h1><p>VYPJ is a youth-led publication creating space for Vietnamese students to research, question, and write about the policies shaping their lives and communities.</p></section><section class="section"><div class="section-head"><h2>Publications</h2><input class="search" id="search" placeholder="Search publications…"></div><div class="grid" id="grid"></div></section>`; const grid=$('#grid'); function draw(){const q=$('#search').value.toLowerCase();const arr=DATA.filter(a=>(a.title+' '+a.author+' '+a.type+' '+a.paragraphs.join(' ')).toLowerCase().includes(q));grid.innerHTML=arr.length?arr.map(card).join(''):`<div class="empty">No publications found.</div>`} $('#search').addEventListener('input',draw);draw()}
function renderArticle(){const q=new URLSearchParams(location.search),a=DATA.find(x=>x.slug===q.get('slug'));const root=$('#content');if(!a){root.innerHTML='<section class="article"><a class="back" href="index.html">← Back to publications</a><h1>Publication not found</h1></section>';return}root.innerHTML=`<article class="article"><a class="back" href="index.html">← All publications</a><div style="margin-top:35px" class="type">${esc(a.type)}</div><h1>${esc(a.title)}</h1><div class="byline">${esc(a.author)}</div><div class="body">${a.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div></article>`}
function renderAbout(){const root=$('#content');root.innerHTML=`<section class="about"><div class="kicker">About VYPJ</div><h1>Vietnamese youth, writing about policy.</h1><p>The Vietnam Youth Policy Journal is a youth-led publication that gives young people a platform to engage with policy, law, society, education, international affairs, and the issues affecting Vietnam.</p><p>This archive preserves the writing produced by VYPJ contributors. Publications are presented as an editorial archive and retain their original authorship and substance.</p></section>`}
const page=document.body.dataset.page;if(page==='article')renderArticle();else if(page==='about')renderAbout();else renderHome();
